### ISSUE TITLE
[Refactor] MVI 패턴 적용

### ISSUE THREAD

**Issue by luke0408** [Say-Better/Android-Educator-APP#13]
## Type of change

- [x] Refactor : 코드 리팩토링 작업
- [x] Document : 문서작업

## Issue Overview

다음과 같은 형태로 프로젝트의 구조를 변경하고자함.

![image](https://github.com/user-attachments/assets/752724a5-a09a-41f0-acb0-4dc80021ebcc)

### 구조 설명

```bash
📦src
 ┗ 📂main.java.com.example.saybetter
   ┃     ┣ 📂 data // --- (1)
   ┃     ┃ ┣ 📂 api
   ┃     ┃ ┃ ┣ 📂 dto
   ┃     ┃ ┃ ┣ 📂 service
   ┃     ┃ ┃ ┗ 📂 Helper
   ┃     ┃ ┣ 📂 model
   ┃     ┃ ┗ 📂 repository
   ┃     ┣ 📂 di
   ┃     ┃ ┗ 📂temp
   ┃     ┣ 📂 ui // --- (2)
   ┃     ┃ ┣ 📂 activity
   ┃     ┃ ┣ 📂 model
   ┃     ┃ ┣ 📂 intent
   ┃     ┃ ┣ 📂 view
   ┃     ┃ ┗ 📂 viewmodel
   ┃     ┗ 📜 APP.kt
   ┗ 📂res
```

DATA : data 처리와 api 연동을 담당하는 패키지

UI : MVI 패턴을 기반으로 veiw 구현을 담당하는 패키지

## Todo

- [x] MVI 패턴 기반 코드 구조 구축
- [x] 기존 코드 리팩토링

**Comment by luke0408** [comment]
## 1.  Layer 단위 분리

```bash
📂 ui
┣ 📂 activity
┣ 📂 model
┣ 📂 intent
┣ 📂 view
┗ 📂 viewmodel
```

[ 장점 ]
- 모아보기 편하다.
- 기능을 중심으로 분류되어 유지보수가 편하다.

[ 단점 ]
- 이후에 프로젝트가 커지면 결국 수정해야 한다.

## 2. page 단위 분리

```bash
📂 ui
┣ 📂 A page
┃ ┣ 📂 activity
┃ ┣ 📂 model
┃ ┣ 📂 intent
┃ ┣ 📂 view
┃ ┗ 📂 viewmodel
┗ 📂 B page
  ┣ 📂 activity
  ┣ 📂 model
  ┣ 📂 intent
  ┣ 📂 view
  ┗ 📂 viewmodel
```

[ 장점 ]
- page 단위로 분리되어있어 작은 단위로 개발하기 편하다.
- 프로젝트가 커지더라도 기존의 구조를 유지할 수 있을 가능성이 높다.

[ 단점 ]
- 결국 각 page를 구성하는 개념의 크기가 크지 않으면 한번에 구조를 이해하기 어려워진다.

## 결과

1번 선택 / 이유: 현재의 프로젝트는 크지 않기 때문에 빠르게 작업하고 넘어가는게 이득이라 판단

**Comment by luke0408** [comment]
## 레이어 구조 구현

> [android 공식 문서](https://developer.android.com/topic/architecture?hl=ko#modern-app-architecture)에서는 다음과 같이 "UI - Domain - Data" 의 레이어 구조를 만들 것을 권장하고 있다.

![image](https://github.com/user-attachments/assets/0d2a89f8-476d-49d1-8f37-698879daf660)

### UI 레이어 구성
---
[ UI elements ]
- UI를 구성하는 기본 요소이다. SayBetter에서는 `ui/view` 페키지에 해당하며 `screen.kt`를 통해 관리한다.

[ UI state ]
- UI 상태(데이터)를 정의한다. SayBetter에서는 `ui/model` 페키지에 해당하며 `model.kt`를 통해 관리한다.

[ UI event ]
- UI 상태 변경에 관여하는 작업을 말한다. SayBetter에서는 `ui/intent` 페키지에 해당하며 `intent.kt`를 통해 관리한다. 

[ ViewModel ]
-  Intent에서 발생하는 SideEffect를 관리한다. SayBetter에서는 `ui/viewmodel` 페키지에 해당하며 `viewmodel.kt`를 통해 관리한다. 

ViewModle이 UI의 상태가 아닌 SideEffect를 담당하는 이유는, "모든 UI변화는 하나의 파일에서 정의된 `intent()`의 실행결과이며, 이를 통해 우리의 어플리케이션에서의 진행 상황에 대해 분명한 이해를 할 수 있으며, 해당 파일을 봤을 때 우리 어플리케이션의 UseCase에 대해 기본적인 이해를 할 수 있어야하기 때문이다."

즉, SideEffect란 `intent()` 와 `model()` 사이에 발생되는 api 호출, DB CURD 등의 UI 외적인 작업을 이야기하며 ViewModel은 `UI 레이어와 Data(혹은 Domain) 레이어 사이의 조율자 역할을 하게 된다.`

### Data 레이어 구성
---
[ Model ]
- 서비스에서 사용되는 `데이터의 개념을 정의`하는데 사용된다. Saybetter에서는  `data/model` 페키지에 해당하며 각 개념에 맞는 이름을 사용한다.

[ Repository ]
- API와 같은 기능을 노출하는 역할을 한다.  Saybetter에서는  `data/api/repository`에 해당한다.

[ DataSource ]
- 서버에 Api를 요청하는 역할을 담당한다.  Saybetter에서는  `data/api/helper`에 해당한다.

**Comment by luke0408** [comment]
## 구조 설계에 대한 고민

1. Local 환경과 network 환경으로 제공되는 repository를 통합할 수 있는 중간자가 필요하다.
2. UI 레이어는 Data 레이어의 정보를 알 수 없도록 분리되어야 한다.
3. 서버의 Data 개념과, 앱의 Data 개념은 다를 수 있으며 종속되어선 안된다.

위 문제를 해결하기 위해 Domain 레이어를 추가하고 useCase를 구현하고자 한다.

**Comment by luke0408** [comment]
## 아키택처 v2

<img width="2814" alt="image" src="https://github.com/user-attachments/assets/7fcb7265-6256-4545-bfa6-216cd4bb8d7d">

```bash
📦src
┗ 📂main.java
  ┣ 📂 com.example.saybetter
  ┃ ┣ 📂 data
  ┃ ┃ ┣ 📂 model
  ┃ ┃ ┣ 📂 local
  ┃ ┃ ┃ ┣ 📂 dto
  ┃ ┃ ┃ ┣ 📂 service
  ┃ ┃ ┃ ┣ 📂 Helper
  ┃ ┃ ┃ ┗ 📂 repository
  ┃ ┃ ┗ 📂 network
  ┃ ┃   ┣ 📂 dto
  ┃ ┃   ┣ 📂 service
  ┃ ┃   ┣ 📂 Helper
  ┃ ┃   ┗ 📂 repository
  ┃ ┣ 📂 domain
  ┃ ┃ ┗ 📂 usecase
  ┃ ┣ 📂 di
  ┃ ┣ 📂 ui
  ┃ ┃ ┣ 📂 activity
  ┃ ┃ ┣ 📂 model
  ┃ ┃ ┣ 📂 intent
  ┃ ┃ ┣ 📂 view
  ┃ ┃ ┗ 📂 viewmodel
  ┃ ┗ 📜 APP.kt
  ┗ 📂res
```

**Comment by luke0408** [comment]
@yeongin-ji @edv-Shin 두분 의견 부탁드립니다!

< 참고 자료 - 공식 문서 >
- https://developer.android.com/topic/architecture?hl=ko
- https://orbit-mvi.org/Android-ViewModel/overview

< 참고 자료 - 블로그 >
- https://proandroiddev.com/mvi-a-new-member-of-the-mv-band-6f7f0d23bc8a
- https://charlezz.com/?p=46365
- https://jaehochoe.medium.com/%EB%B2%88%EC%97%AD-%EC%83%81%ED%83%9C-%EC%A7%80%ED%96%A5-%EC%95%84%ED%82%A4%ED%85%8D%EC%B2%98-mvi%EB%A5%BC-%EC%86%8C%EA%B0%9C%ED%95%A9%EB%8B%88%EB%8B%A4-mvi-on-android-725cae5b1753

< 참고 자료 - github >
- https://github.com/MindorksOpenSource/MVI-Architecture-Android-Beginners
- https://github.com/jurajkusnier/stock-browser
- https://github.com/Charlezz/MVIExample

**Comment by yeongin-ji** [comment]
success에서 양갈래로 나가는 화살표의 의미는 받아온 API Server 혹은 Local DB의 데이터를, Helper를 이용해서 정의된 dto에 맞추는 경우도 있고 그냥 바로 Entity에 반영되는 경우도 있기 때문에 이러한 두 가지 경우를 모두 표현하기 위해 사용된 것이라고 이해해도 될까요?

**Comment by luke0408** [comment]
성공과 실패에 대한 이야기 였는데 다이어그램에 그게 빠졌군요...!

성공하면 DTO가 반환되어 Helper를 통해 Entity가 변환되고, 실패하면 Entity가 null로 생성이 되거나 기존의 상태값을 유지한다는 의미입니다!

**Comment by yeongin-ji** [comment]
아하 성공과 실패와 관련된 화살표였군요..! 이해했습니다. 얕은 지식을 가진 입장에서 보아도 좋은 구조라고 생각해요!

**Comment by luke0408** [comment]
저도.. 안드가 처음이라....... 사실 영인님이 저보다 안드 오래하셨잖아요... ㅋㅋㄱㅋㄱㅋㄱ

**Comment by yeongin-ji** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 그.. 물경력 입니다 ㅎㅎ

**Comment by edv-Shin** [comment]
Local, NetworkRepository를 따로 두지 않고, 하나의 Repository에서 Local Helper(DataSource), Network Helper(DataSource) 중 적절한 것을 선택하여 내려주는 방식이 일반적인 안드로이드 아키텍쳐에 맞을 것 같습니다.
