### ISSUE TITLE
[Refactor] 빌드 정상화

### ISSUE THREAD

**Issue by edv-Shin** [Say-Better/Android-Educator-APP#16]
## Type of change

- [x] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업

## Issue Overview

- 구조 리팩토링에 따라 빌드 정상화 작업

## Todo

- [x] 기존 Application 클래스 삭제 
- [x] MainActivity의 HomeScreen화
