### ISSUE TITLE
[Refactor] webrtc 코드를 MVI 패턴으로 마이그레이션

### ISSUE THREAD

**Issue by yeongin-ji** [Say-Better/Android-Educator-APP#17]
## Type of change

- [ ] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [x] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [x] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## Issue Overview

기존 utils 폴더 내에 들어있던 webrtc 관련 파일 및 코드 내용을 현 개발패턴(MVI)에 맞게 재조직하는 과정입니다.
재조직 후에도 화상 통화가 잘 동작해야 하며, 구조의 일관성을 통해 개발 속도를 향상하는 것이 목표입니다.
이 과정에서 변수 및 함수 이름 변경이 있을 수 있습니다.

## Todo

- [x] 디자인 요구사항에 맞는 해상도 구현 (~8/9)
- [x] 디자인 요구사항에 맞는 캠 위치 구현 (~8/9)
- [ ] Ping 확인 기능 추가 (~8/10)
