### ISSUE TITLE
[Feature] 솔루션 진행 화면 ui 개발

### ISSUE THREAD

**Issue by edv-Shin** [Say-Better/Android-Educator-APP#19]
## Type of change

- [x] Feature : 새로운 기능 추가

## Issue Overview

<img width="891" alt="image" src="https://github.com/user-attachments/assets/18b94e32-f0eb-4507-bacd-2184ee5ee28a">
- mvi 패턴에 맞게 솔루션 진행 화면 ui 개발

## Todo

- [x] 바텀시트 ui
- [x] 상징 카드 ui
- [ ] 바텀시트-상징 카드 상호작용 구현
