### ISSUE TITLE
[Feat] WebRTC 즉각적인 상호작용 구현

### ISSUE THREAD

**Issue by yeongin-ji** [Say-Better/Android-Educator-APP#25]
## Type of change

- [x] Feature : 새로운 기능 추가

## Issue Overview

교육자가 상징을 터치할 경우 나타나는 반응이 학습자 앱에서도 동일하게 나타나야 합니다.

## Todo

- [x] 솔루션 진행 초반에서의 상호 간 인사 구현
- [x] 필드에 제시된 상징 공유
- [x] 필드 레이아웃 상태 공유
- [x] 그림상징에 대한 즉각적인 상호작용
- [ ] 예/아니오 구현
