### ISSUE TITLE
[Feature] 메인화면 Bottom Navigation 구현

### ISSUE THREAD

**Issue by yeongin-ji** [Say-Better/Android-Educator-APP#3]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## Issue Overview

Educator APP 메인 화면에서 바텀 네비게이션을 구현합니다.

## Todo

- [x] 바텀네비 기능구현
- [x] 디자인 Hand-off 완료

**Comment by yeongin-ji** [comment]
Todo: 기본 제공되는 Ripple 효과 커스터마이징
