### ISSUE TITLE
[Feature] WebRTC Greeting 단계에서의 text 전송 기능 추가

### ISSUE THREAD

**Issue by yeongin-ji** [Say-Better/Android-Educator-APP#32]
## Type of change

- [x] Feature : 새로운 기능 추가

## Issue Overview

학습자, 교육자 간 양방향 의사소통을 지원하기 위해 DataChannel을 통해 텍스트를 전송할 수 있도록 합니다.
또한, 솔루션 종료 전 Greeting 단계를 추가하여 상호 간 인사 후에 솔루션을 종료할 수 있도록 합니다.

## Todo

- [x] Text 전송 on DataChannel
- [x] 솔루션 종료 전 Greeting 단계 추가
