### ISSUE TITLE
[Bug] 즉각적인 상호작용: 상징 강조 표시 및 음성 산출이 일부만 동작하는 버그 수정

### ISSUE THREAD

**Issue by yeongin-ji** [Say-Better/Android-Educator-APP#33]
## Type of change

- [x] Bug fix : 버그 수정

## Issue Overview

WebRTC 구현에서 즉각적인 상호작용이 일부만 동작하는 버그를 수정합니다.

## Todo

- [x] 교육자 앱에서 음성 산출 볼륨이 작아지는 버그 수정
- [x] 상징 음성 산출 이후에도 강조 표시가 사라지지 않는 버그 수정
