### ISSUE TITLE
[Feature] webrtc 텍스트 상징 기능 구현

### ISSUE THREAD

**Issue by yeongin-ji** [Say-Better/Android-Educator-APP#37]
## Type of change

- [x] Feature : 새로운 기능 추가

## Issue Overview

다소 디테일한 단어의 경우 없는 상징이 있을 수 있으므로 실시간 통신 상황에서 텍스트를 입력하여 임시 텍스트 상징을 사용할 수 있도록 합니다.

## Todo

- [ ] 텍스트 입력 창 구현
- [ ] 텍스트 상징 양쪽에 모두 추가되도록 구현
