### ISSUE TITLE
[Feature] 바텀네비 Item - HomeScreen 구현

### ISSUE THREAD

**Issue by yeongin-ji** [Say-Better/Android-Educator-APP#4]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## Issue Overview

- 바텀네비에서의 홈 화면을 디자인 및 VideoCall 화면으로의 연결을 구현합니다.

## Todo

- [ ] HomeScreen 디자인 Hand-off 완료
- [ ] 솔루션 항목 Clickable 구현: VideoCall 화면으로의 연결
