### ISSUE TITLE
[Feature] VideoCall 화면 및 주요 상호작용 구현

### ISSUE THREAD

**Issue by yeongin-ji** [Say-Better/Android-Educator-APP#5]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## Issue Overview

- VideoCall 화면 디자인 Hand-off 완료하고 터치시 반응, 레이아웃 변경 기능을 구현합니다.

## Todo

- [x] VideoCall 화면 디자인 Hand-off 완료
- [ ] 상징 터치 반응 구현
- [ ] 상징 레이아웃 변경 기능 구현
