### ISSUE TITLE
[Feature] VideoCall - WebRTC 화상통화 구현

### ISSUE THREAD

**Issue by yeongin-ji** [Say-Better/Android-Educator-APP#6]
## Type of change

- [x] Feature : 새로운 기능 추가
- [ ] Bug fix : 버그 수정
- [ ] Refactor : 코드 리팩토링 작업
- [ ] Document : 문서작업
- [ ] Test : 테스트 코드 작성 및 테스트 작업
- [ ] Style : 코드 스타일 및 포맷팅 작업
- [ ] CI/CD : CI/CD 작업 수정
- [ ] Chore : 패키지 매니저, 라이브러리 업데이트 등의 작업

## Issue Overview

- Android Learner APP에 구현된 실시간 화상통화 기능을 Educator APP으로 옮깁니다.

## Todo

- [x] Hilt, Gson, WebRTC 종속성 추가
- [x] Hilt 의존성 주입 적용
- [x] Firebase 앱 등록 및 종속성 추가
- [x] ForegroundService 실행
- [x] onLatestEvent 감지 테스트
- [x] 카메라, 마이크 권한 설정
- [x] 화상통화 요청 전송 및 VideoCallActivity 전환
- [x] LocalSurfaceView 구현
- [x] Turn Server 등록 및 RemoteSurfaceView 구현
- [x] 화상통화 종료 버튼 구현
- [x] 마이크, 카메라 on/off 버튼 구현
- [x] 카메라 전면/후면 전환 버튼 구현
